Makefile: codesign with -o kill,hard,expires instead of -o runtime
ProcursusTeam/Procursus pull request #1038
Opened 2021-10-07 12:57 UTC by CRKatri

runtime includes library validation, which requires any libraries to be
system or signed with the same Team ID in order to be loaded, this means
that anything signed with a valid cert that is not part of Hayden Seay's
team will not work.

\> ldid
dyld: Library not loaded: @rpath/libcrypto.3.dylib
  Referenced from: /opt/procursus/bin/ldid
  Reason: no suitable image found.  Did find:
    /opt/procursus/lib/libcrypto.3.dylib: code signature in (/opt/procursus/lib/libcrypto.3.dylib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
    /opt/procursus/lib/libcrypto.3.dylib: stat() failed with errno=1
[1]    12218 abort      ldid

2021-10-10 22:52 UTC, Diatrus commented
Sign with ldid adhoc too in this PR

2021-11-12 16:34 UTC, sunflsks requested changes
remove the `expires` flag please

2021-11-12 16:37 UTC, sunflsks approved these changes

2021-11-12 16:37 UTC, sunflsks approved these changes

2021-11-12 16:38 UTC, merged