Rootless bugfixes
ProcursusTeam/Procursus pull request #1237
Opened 2022-05-07 04:50 UTC by captinc

### All Submissions

* [ ] Have you made sure there aren't any other open [Pull Requests](https://github.com/ProcursusTeam/Procursus/pulls) for the same update/change?
* [ ] This Pull Request doesn't contain any package additions; it's a small change (e.g README change)

### Package Additions/Updates

* [ ] Have you confirmed this builds & works as intended on an iOS device (if applicable)?
* [ ] Have you confirmed this builds & works as intended on a macOS device (if applicable)?

### Details

Various: 

* fixes for build errors
* fixes for rootless path issues (when a built .deb has files outside /private/preboot/procursus, which is illegal on a rootless platform)
* updates to package versions
* a little trolling

Also, note: there are still issues when compiling dpkg and gettext. That should be looked into. The gettext issue is some sort of race condition, so be careful with parallel builds and such

- cameren smells

2022-05-07 04:59 UTC, captinc commented
Sidenote, compilation fails with Xcode Command Line Tools 13.3 and newer. You have to use 13.2.1 or older

2022-05-08 02:11 UTC, TheRealKeto requested changes
Just some QOL suggestions; did you test other targets as well? I fear some of these changes will have negative effects on other targets.

2022-05-08 02:11 UTC, TheRealKeto commented on makefiles/lsof.mk
> +
Delete this blank line

```suggestion
	$(call DO_PATCH,lsof,lsof,-p1)
```

2022-05-08 02:11 UTC, TheRealKeto commented on makefiles/network-cmds.mk
> +		$(LN_S) ../$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/sbin/$$bin $(BUILD_STAGE)/network-cmds/$(MEMO_PREFIX)sbin; \
Use the correct prefix, per suggestion

```suggestion
		$(LN_S) ../$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/sbin/$$bin $(BUILD_STAGE)/network-cmds/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/sbin; \
```

2022-05-08 02:11 UTC, TheRealKeto commented on makefiles/network-cmds.mk
> +	$(LN_S) ../$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/sbin/ping6 $(BUILD_STAGE)/network-cmds/$(MEMO_PREFIX)bin
Again, use the correct prefix...

```suggestion
	$(LN_S) ../$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/sbin/ping6 $(BUILD_STAGE)/network-cmds/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/bin
```

2022-05-08 02:36 UTC, captinc commented
Good point, I have not tested other targets; QOL suggestions added

2022-07-27 16:18 UTC, closed without merging