Added jansson and cpuminer added cpuminer and jansson
ProcursusTeam/Procursus pull request #135
Opened 2020-09-20 14:01 UTC by demhademha

2020-10-06 13:54 UTC, a0ahmad approved these changes

2020-10-06 14:08 UTC, CRKatri requested changes

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +			--host=$(GNU_HOST_TRIPPLE) \
`GNU_HOST_TRIPLE`, not `GNU_HOST_TRIPPLE`

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +	--prefix=/usr
Nothing serious, but this indention needs fixing.

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +	rm -rf $(BUILD_DIST)/*jansson*/
Don't use wildcards here, it'll remove the deb.

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +	rm -rf $(BUILD_DIST)/*jansson*/
Don't use wildcards here, it'll remove the deb.

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
>  	$(call SIGN,jansson,general.xml)
You need to sign the libraries

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +	mkdir -p $(BUILD_DIST)/jansson/usr \
Unnecessarily making `$(BUILD_DIST)/jansson/usr/` which doesnt get used.

2020-10-06 14:08 UTC, CRKatri commented on build_info/jansson.control
> +Package: jansson
This control files never gets used, it can be removed.

2020-10-06 14:08 UTC, CRKatri commented on build_info/cpuminer.control
> +Depends: jansson, curl
This should depend on `libjansson4`

2020-10-06 14:08 UTC, CRKatri commented on build_info/libjansson-dev.control
> +Tag: purpose::console, role::developer
Add, `Depends: libjansson4 (= @DEB_JANSSON_V@)`

2020-10-06 14:08 UTC, CRKatri commented on build_info/libjansson-dev.control
> +Section: Libraries
Should go in the `Development` section.

2020-10-06 14:08 UTC, CRKatri commented on jansson.mk
> +	$(call PACK,jansson,DEB_JANSSON_V)
This can be removed.

2020-10-06 14:43 UTC, a0ahmad approved these changes

2020-10-06 16:13 UTC, demhademha commented
@CRKatri should be fixed now.

2020-10-08 10:52 UTC, Diatrus approved these changes
Thank you very much for the contribution. It means a lot!

2020-10-08 10:52 UTC, merged