Add binutils
ProcursusTeam/Procursus pull request #520
Opened 2021-03-16 20:21 UTC by CRKatri

2021-03-16 20:30 UTC, Diatrus requested changes

2021-03-16 20:30 UTC, Diatrus commented on binutils.mk
> +	$(call SIGN,binutils-aarch64-linux-gnu,general.xml)
Would doing a for $$target loop in the SIGN and PACK stages decrease the size of this makefile? Also, great to see you're still alive. :)

2021-04-05 17:11 UTC, Diatrus commented
Last time I tried this it didn't even get close to building on macOS. If you can, can you give it another try?

2021-04-05 20:16 UTC, CRKatri commented
I removed the BSD targets, cause a bunch of them didn't work, I don't have a Mac or Mac VM to test building them on MacOS, sorry.

2021-05-28 11:02 UTC, CRKatri commented
None wants binutils when you can use llvm #779

2021-05-28 11:03 UTC, closed without merging