add libpam-google-authenticator
ProcursusTeam/Procursus pull request #556
Opened 2021-03-24 17:14 UTC by demhademha

2021-03-24 17:41 UTC, sunflsks approved these changes

2021-03-29 09:48 UTC, 1Conan requested changes

2021-03-29 09:48 UTC, 1Conan commented on libpam-google-authenticator.mk
> +		&& wget -nc -O$(BUILD_SOURCE)/libpam-google-authenticator-$(LIBPAM-GOOGLE-AUTHENTICATOR_COMMIT).tar.gz \
missing -q flag

2021-03-29 09:48 UTC, 1Conan commented on libpam-google-authenticator.mk
> +			+$(MAKE) -C $(BUILD_WORK)/libpam-google-authenticator
indentation

2021-03-29 09:48 UTC, 1Conan commented on libpam-google-authenticator.mk
> +		touch $(BUILD_WORK)/libpam-google-authenticator/.build_complete
indentation

2021-03-29 09:48 UTC, 1Conan commented on libpam-google-authenticator.mk
> +	mv -f $(BUILD_DIST)/libpam-google-authenticator$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/security $(BUILD_DIST)/libpam-google-authenticator$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/pam
missing `/`s

2021-04-05 07:23 UTC, merged