Add pup
ProcursusTeam/Procursus pull request #596
Opened 2021-04-03 15:09 UTC by CRKatri

2021-04-05 09:19 UTC, Diatrus commented
Waiting on golang amd64

2021-04-27 04:03 UTC, Diatrus commented
Please update to use the common golang arguments

2021-04-29 02:57 UTC, Diatrus commented
Since this project seems inactive, can you switch this to use the latest commit? (I'm sure you know the format for git commit packages) 👍

2021-04-29 03:22 UTC, TheRealKeto requested changes

2021-04-29 03:22 UTC, TheRealKeto commented on pup.mk
> +			https://github.com/ericchiang/pup/archive/v$(PUP_VERSION).tar.gz
Stop using this.. we have the ``GITHUB_ARCHIVE`` function for a reason.

2021-04-29 03:22 UTC, TheRealKeto commented on pup.mk
> +	cp -a $(BUILD_STAGE)/pup $(BUILD_DIST)/
Remove the slash after ``$(BUILD_DIST)``; it's not needed.

2021-04-30 05:14 UTC, merged