As2
ProcursusTeam/Procursus pull request #612
Opened 2021-04-09 02:01 UTC by asdfugil

add haydenfetch. Supersedes #611 .

2021-04-09 02:03 UTC, asdfugil commented
this should satisfy all suggestions in #611 .

2021-04-09 03:21 UTC, TheRealKeto approved these changes
Approved.

2021-04-09 03:25 UTC, brennanleblanc0 approved these changes

2021-04-09 03:28 UTC, 1Conan requested changes

2021-04-09 03:28 UTC, 1Conan commented on haydenfetch.mk
> +	wget -q -nc -P $(BUILD_SOURCE) https://github.com/asdfugil/haydenfetch/archive/refs/tags/v$(HAYDENFETCH_VERSION).tar.gz
Use GITHUB_ARCHIVE function

2021-04-09 19:05 UTC, 1Conan approved these changes

2021-04-10 06:36 UTC, asdfugil commented
- fixed bad substitution error on some jailbreaks due to shebang not being respected
- added help message
- add more haydens

2021-04-12 05:58 UTC, closed without merging

2021-04-14 12:40 UTC, asdfugil commented
bruh when did I close this