Add siguza-utils
ProcursusTeam/Procursus pull request #623
Opened 2021-04-11 03:37 UTC by TheRealKeto

This PR adds ``siguza-utils``, which includes ``bindump``, ``clz``, ``dsc_syms``, ``rand``, ``strerror``, ``vmacho``, and ``xref`` from [Siguza/misc](https://github.com/Siguza/misc), in one package. The only exception is ``mesu``, which seems to no longer work.

This is my first, somewhat usable package (that isn't just a control file), so I do suggest giving me critism on how I've compiled this. I've attempted to use functions which make things like downloading and extracting a package easier, but I'm sure this can be improved. Software provided as-is, blah blah not much from here will do anything bad.

2021-04-11 03:40 UTC, Diatrus requested changes
Overall looks great, just a couple surface-level quirks I see from a quick scan. Nice description btw.

2021-04-11 03:40 UTC, Diatrus commented on siguza-utils.mk
> +SUPROJECTS      += siguza-utils
No need to have a LIBS var for just one tool. Just put the libs/frameworks after the ldflags.

2021-04-11 03:40 UTC, Diatrus commented on build_info/siguza-utils.control
> +Tag: purpose::console, role::hacker
I try to avoid using Tag: as of late.

2021-04-11 07:58 UTC, Cryptiiiic commented on build_info/siguza-utils.control
> -Tag: purpose::console, role::hacker
no one likes u get lost

2021-04-11 13:26 UTC, CRKatri requested changes

2021-04-11 13:26 UTC, CRKatri commented on siguza-utils.mk
> +	$(call EXTRACT_TAR,misc-$(MISC_COMMIT).tar.gz,misc-$(MISC_COMMIT),misc)
Change arg 3 from `misc` to `siguza-utils` and delete line 23

2021-04-11 13:26 UTC, CRKatri commented on siguza-utils.mk
> +	$(call GITHUB_ARCHIVE,Siguza,misc,$(MISC_COMMIT),$(MISC_COMMIT))
Use arg 4 when changing the name of the tarball (look at ghostbin for reference)

2021-04-11 16:16 UTC, TheRealKeto commented on build_info/siguza-utils.control
> -Tag: purpose::console, role::hacker
this is a banger

2021-04-11 17:38 UTC, TheRealKeto commented
The latest 2 commits should accommodate with all requested changes.

2021-04-13 05:59 UTC, Diatrus requested changes

2021-04-13 05:59 UTC, Diatrus commented on siguza-utils.mk
> +MISC_COMMIT     := 43852780a20ebf2c990681aa1ab42577ae630555
name these SIGUZA-UTILS_{COMMIT,VERSION,etc} for consistency please

2021-04-14 19:22 UTC, merged