Added bpytop for macOS and iOS.
ProcursusTeam/Procursus pull request #641
Opened 2021-04-13 20:12 UTC by DaOfficialRolex

2021-04-13 21:41 UTC, DaOfficialRolex commented
It should be noted that this doesn't work without python-psutil. This will be converted into a draft for the time being until that psutil is added and merged into as2 branch.

2021-04-18 12:25 UTC, Cryptiiiic commented
This pull works out of the box on iOS given that you have python3-psutil.
![image](https://user-images.githubusercontent.com/27748705/115145455-7f3ec480-a006-11eb-92df-86a455995b46.png)

2021-05-23 18:13 UTC, Diatrus requested changes

2021-05-23 18:13 UTC, Diatrus commented on bpytop.mk
> +	wget -q -nc -P $(BUILD_SOURCE)  https://github.com/aristocratos/bpytop/archive/refs/tags/v$(BPYTOP_VERSION).tar.gz
GITHUB_ARCHIVE? :)

2021-05-23 18:13 UTC, Diatrus commented on bpytop.mk
> +BPYTOP_VERSION := 1.0.63
There's a newer version now

2021-05-23 18:27 UTC, merged