Add chezmoi
ProcursusTeam/Procursus pull request #645
Opened 2021-04-15 21:54 UTC by Randomblock1

Add chezmoi from https://github.com/twpayne/chezmoi
Needs Go 1.16 (#579), and it compiles just fine on my iPhone and ARM Mac.

2021-04-15 21:58 UTC, Diatrus commented
Going to wait to merge until I do golang 1.16. Should hopefully be merged today. 👍

2021-04-16 00:37 UTC, quiprr requested changes

2021-04-16 00:37 UTC, quiprr commented on chezmoi.mk
> +		CC=cc \
Shouldn't this be $(CC)?

2021-04-16 00:43 UTC, Randomblock1 commented on chezmoi.mk
> +		CC=cc \
Whoops, yes it should be.

2021-04-17 21:51 UTC, Diatrus commented
@Randomblock1 would you mind updating this PR to use the new DEFAULT_GOLANG_FLAGS variable from commit f63bcf3216d8a31f8454d17c6018657677220aac? It should remove the need for any of that GO_ARGS stuff.

2021-04-18 01:45 UTC, Randomblock1 commented
OK, it should work with the new variables now.

2021-04-18 05:13 UTC, Diatrus commented
Thank you

2021-04-18 05:13 UTC, merged