x11-session-utils
ProcursusTeam/Procursus pull request #662
Opened 2021-04-20 00:18 UTC by Gymxo

And before you ask, yes this is debianized https://packages.debian.org/source/sid/x11-session-utils

2021-06-28 05:49 UTC, m1stadev requested changes

2021-06-28 05:49 UTC, m1stadev commented on x11-session-utils.mk
> +SUBPROJECTS   += x11-session-utils
Spacing.

2021-06-28 05:49 UTC, m1stadev commented on x11-session-utils.mk
> +	+$(MAKE) -C $(BUILD_WORK)/x11-session-utils/xsm
This could be condensed into a for loop.

2021-07-10 04:53 UTC, Gymxo commented
Have more important things

2021-07-10 04:53 UTC, closed without merging