add mawk
ProcursusTeam/Procursus pull request #699
Opened 2021-05-01 19:48 UTC by demhademha

I'm not sure aobut versioning

2021-05-01 20:20 UTC, demhademha commented
This is done, I'm just unsure about versioning

2021-05-01 20:29 UTC, TheRealKeto requested changes
Please unmark this as a draft once the following changes have been made.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +
Remove this line...

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +	rm -rf $(BUILD_DIST)/mawk
Add spaces between comments; improves readability.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +	$(DEFAULT_CONFIGURE_FLAGS)
Indent this line.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +endif
Add a space after this line.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +ifneq ($(wildcard $(BUILD_WORK)/mawk/.build_complete),)
Add a space before this line.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +endif
Add a space after this line.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +	wget -q -nc -P$(BUILD_SOURCE) http://deb.debian.org/debian/pool/main/m/mawk/mawk_$(MAWK_VERSION).$(MAWK_COMMIT).orig.tar.gz
Add a space after line 8. Add a space after the argument, -P; improves readability.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +DEB_MAWK_V   ?= $(MAWK_VERSION)
Fix the spacing of your vars.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +.PHONY: mawk mawk-package
Add a space before this line.

2021-05-01 20:29 UTC, TheRealKeto commented on mawk.mk
> +mawk-setup: setup
Add a space above this line.

2021-05-01 20:29 UTC, TheRealKeto commented on build_info/mawk.control
> +Priority: required
Change this to optional.

2021-05-01 21:07 UTC, TheRealKeto requested changes

2021-05-01 21:07 UTC, TheRealKeto commented on mawk.mk
> +	.PHONY: mawk mawk-package
De-dent and add a space before this line.

2021-05-03 16:09 UTC, CRKatri commented
Add the postinst and postrm (https://salsa.debian.org/debian/mawk/-/blob/master/debian/mawk.postinst) and do the same for gawk, and make them both provide the awk package.

2021-05-10 00:28 UTC, merged