add dwm
ProcursusTeam/Procursus pull request #718
Opened 2021-05-07 03:46 UTC by asdfugil

well, that took some time to figure out
![remmina_iPad_192 168 0 102:5901_202157-34431 014265](https://user-images.githubusercontent.com/42699250/117395007-d101ad00-af29-11eb-92ab-4206fccbd2f1.png)

2021-05-07 13:32 UTC, Gymxo requested changes

2021-05-07 13:32 UTC, Gymxo commented on dwm.mk
> +	cd $(BUILD_WORK)/dwm; \
What's the point of this cd here?

2021-05-07 14:01 UTC, asdfugil commented on dwm.mk
> +	cd $(BUILD_WORK)/dwm; \
no point

2021-05-08 13:18 UTC, asdfugil commented
Don't merge yet because I want to enable libxinerama

2021-05-08 17:52 UTC, CRKatri commented
How do you start this? Do we have xinit?

2021-05-08 17:54 UTC, Gymxo commented
In this case it’s probably dwm hence the name

2021-05-08 17:55 UTC, CRKatri commented
I know that but xinit is a cleaner way, I just didn’t know if pro had it

2021-05-08 17:58 UTC, Gymxo commented
I can send a pr if wanted since it’s basically almost done on my end

2021-06-11 05:33 UTC, m1stadev requested changes

2021-06-11 05:33 UTC, m1stadev commented on dwm.mk
> +	$(SED) -i 's/{ "st", NULL };/{ "xterm", "-bg", "black", "-fg", "lightgray", NULL };/g' $(BUILD_WORK)/dwm/config.def.h
Move these sed calls to a patch.

2021-06-26 07:49 UTC, asdfugil commented
@m1stadev looks good to me

2021-10-05 11:25 UTC, Gymxo approved these changes

2021-10-05 11:27 UTC, Gymxo commented on makefiles/dwm.mk
> +	mkdir -p $(BUILD_DIST)/dwm
Remove line 28 of the dwm.mk

2021-10-05 11:32 UTC, asdfugil commented on makefiles/dwm.mk
> +	mkdir -p $(BUILD_DIST)/dwm
```suggestion
```

2021-10-05 11:33 UTC, Gymxo commented on makefiles/dwm.mk
> +	mkdir -p $(BUILD_DIST)/dwm
Yeah I hate the ui on mobile safari

2021-10-05 11:33 UTC, Gymxo approved these changes

2022-03-03 04:06 UTC, asdfugil commented
By the way, I did not have a breakdown - I just can't allow myself to be distracted while I do something much more important and takes time.

2022-03-03 04:16 UTC, asdfugil commented
The current ETA is afternoon of 6 May 2022 (UTC+8), but is prone to delays.

2022-05-17 13:59 UTC, asdfugil commented
`build_tools/compile.sh` works fine. Also CFLAGS is now properly set as opposed to using -Wno-error-implicit-function-declaration

2022-07-15 09:09 UTC, asdfugil commented
bingo

2022-07-15 09:09 UTC, closed without merging