Fix APT 404 Errors on unsupported platforms.
ProcursusTeam/Procursus pull request #787
Opened 2021-05-30 11:30 UTC by asdfugil

This fixes apt 404 errors caused by the absence of repository on unsupported platforms.

2021-05-31 17:16 UTC, Diatrus requested changes

2021-05-31 17:16 UTC, Diatrus commented on Makefile
> -
Don't remove any extra whitespace for no reason.

2021-05-31 17:16 UTC, Diatrus commented on Makefile
> +ifneq (,$(findstring 404 Not Found,$(shell wget -qO- $(MEMO_REPO_URI)/dists/$(MEMO_TARGET)/$(MEMO_CFVER) --content-on-error || ([ "$$?" -eq 8 ] && true) || false)))
Don't do this

2021-05-31 17:16 UTC, Diatrus commented on Makefile
> +ifneq (,$(findstring 404 Not Found,$(shell wget -qO- $(MEMO_REPO_URI)/dists/$(MACOSX_SUITE_NAME)/main --content-on-error || ([ "$$?" -eq "8" ] && true) || false)))
Don't do this

2021-06-06 16:35 UTC, asdfugil commented
not the most useful thing ever. closing.

2021-06-06 16:35 UTC, closed without merging