New README and guidelines
ProcursusTeam/Procursus pull request #832
Opened 2021-06-22 23:25 UTC by TheRealKeto

This PR provides a much cleaner README, removing all references of documentation of the project, since that's been moved to the project's [wiki page](https://github.com/ProcursusTeam/Procursus), while also providing cleaner contribution guidelines.

I probably made a few typos here and there; just tell me through a PR review and I'll change it when I can.

2021-06-22 23:28 UTC, quiprr requested changes

2021-06-22 23:28 UTC, quiprr commented on README.md
> +A new, powerful, cross-compilation *OS boostrap. At its core, Procursus is a build-system that provides a large set of consistently up-to-date *nix tools cross compiled to work on Darwin based platfo
misspelled bootstrap

2021-06-22 23:37 UTC, m1stadev commented
readme dev strikes again

2021-06-22 23:49 UTC, TheRealKeto commented on README.md
> +A new, powerful, cross-compilation *OS boostrap. At its core, Procursus is a build-system that provides a large set of consistently up-to-date *nix tools cross compiled to work on Darwin based platfo
Resolved with latest PR commit.

2021-06-23 01:00 UTC, CRKatri commented
Could you transfer the wiki to be in a sub folder of the repo or even a separate repo so that the wiki can be accessed easily.

2021-06-23 01:07 UTC, TheRealKeto commented
No. I see no point in that. Just visit the website; the transition was done so this wouldn't be a thing.

The wiki itself can be locally clone too, in case you really need the files.

2021-06-23 01:09 UTC, CRKatri commented
It also allows us to make the wiki read only and have PRs for it.

2021-06-23 02:54 UTC, TheRealKeto commented
The wiki is already read only. PRs to the wiki is something that would have low traffic.

2021-06-24 23:13 UTC, merged

2021-06-25 18:47 UTC, TheRealKeto commented
@CRKatri Since you asked for it, [here you go,](https://github.com/TheRealKeto/procursus-docs)

2021-06-25 19:03 UTC, CRKatri commented
It’s missing _Sidebar.md, it should be in the ProcursusTeam Org, and you should setup something similar to https://github.com/theos/theos-wiki/blob/main/.github/workflows/publish-wiki.yml. Personal I also think it’d be better as a docs sub folder in the main repo, but that’s up to @Diatrus.

2021-06-25 19:05 UTC, Diatrus commented
I agree with that sentiment @CRKatri

2021-06-25 19:05 UTC, TheRealKeto commented
The sidebar is irrelevant to the actual documentation; I pushed it under my own Github profile because I can't create repositories under the org, and doing a workflow is up to Hayden.