Add libcdio
ProcursusTeam/Procursus pull request #908
Opened 2021-07-17 13:24 UTC by asdfugil

udf, iso9660, cddb, cd-rom, iso images libraries and utilities.

2021-07-29 06:11 UTC, TheRealKeto requested changes
This took me a long time for some reason...

2021-07-29 06:11 UTC, TheRealKeto commented on build_info/libcdio-dev.control
> + This package contains the header files and static library needed to compile applications that use libcdio.
So many damn control files....

```suggestion
Description: development files for libcdio.
 This library is to encapsulate CD-ROM reading and control. Applications
 wishing to be oblivious of the OS- and device-dependant properties of a
 CD-ROM can use this library. Some support for disk image types like BIN/CUE
 and NRG is available, so applications that use this library also have the ability
 to read disc images as though they were CD's. This package contains the header
 files and static library needed to compile applications that use libcdio.
```

2021-07-29 06:11 UTC, TheRealKeto commented on build_info/libcdio++1.control
> + Some support for disk image types like BIN/CUE and NRG is available, so applications that use this library also have the ability to read disc images as though they were CD's.
Why does this need to be debianized into so many packages.....

```suggestion
Description: C++ library to read and control CD-ROM.
 This C++ library is to encapsulate CD-ROM reading and control. Applications
 wishing to be oblivious of the OS- and device-dependant properties of a CD-ROM
 can use this library. Some support for disk image types like BIN/CUE and NRG is available,
 so applications that use this library also have the ability to read disc images as though
 they were CD's.
```

2021-07-29 06:11 UTC, TheRealKeto commented on build_info/libcdio++-dev.control
> + Some support for disk image types like BIN/CUE and NRG is available, so applications that use this library also have the ability to read disc images as though they were CD's.
Please stop with all of these control files......

```suggestion
Description: C++ library to read and control CD-ROM (development files).
 This package contains development files (headers and static library) for the
 libcdio++ library. This library is to encapsulate CD-ROM reading and control.
 Applications wishing to be oblivious of the OS- and device-dependant properties
 of a CD-ROM can use this library. Some support for disk image types like BIN/CUE
 and NRG is available, so applications that use this library also have the ability
 to read disc images as though they were CD's.
```

2021-07-29 06:11 UTC, TheRealKeto commented on build_info/libcddb2.control
> + This package contains the libcddb runtime library.
Stop copypasting Debian's control file

```suggestion
Description: library to access CDDB data.
 libcddb is a C library to access data about Audio CD
 on a CDDB server. It allows one to search the database for
 CD matches, get detailed information about a CD and submit
 new CD entries to the database. It supports both the custom
 CDDB protocol and the tunneling of the query over HTTP. HTTP
 Proxying is supported. It also features a cache system. This
 package contains the libcddb runtime library.
```

2021-07-29 06:11 UTC, TheRealKeto commented on build_info/libcddb2-dev.control
> + This package contains the header files and static library needed to compile applications that use libcddb.
Last control file, finally.

```suggestion
Description: development files for libcddb.
 libcddb is a C library to access data about Audio CD
 on a CDDB server. It allows one to search the database
 for CD matches, get detailed information about a CD and
 submit new CD entries to the database. It supports both
 the custom CDDB protocol and the tunneling of the query
 over HTTP. HTTP Proxying is supported. It also features a
 cache system. This package contains the header files and
 static library needed to compile applications that use
 libcddb.
```

2022-01-03 21:16 UTC, CRKatri approved these changes

2022-01-03 21:16 UTC, merged