Full WebAssembly toolchain
ProcursusTeam/Procursus pull request #930
Opened 2021-07-31 16:23 UTC by Absolucy

This is a *full WebAssembly toolchain* for Procursus.  
It includes:
 - `build-essential-wasi`: A wasm32-wasi SDK/sysroot.
 - `binaryen`: A WebAssembly optimizer
 - `wabt`: Various WebAssembly tools
 - `wasmer`: A WebAssembly runtime (+ C API in `libwasmer`)

2021-07-31 16:35 UTC, Absolucy commented
Note: wasmer won't build on iOS currently.

2021-07-31 17:50 UTC, TheRealKeto requested changes
QOL changes, only.

2021-07-31 17:50 UTC, TheRealKeto commented on makefiles/wasmer.mk
> +	$(INSTALL) -Dm755 $(BUILD_STAGE)/libwasmer/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libwasmer.dylib $(BUILD_DIST)/libwasmer/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libwasmer.dylib
Just copy to build_dist, instead. 

```suggestion
	cp -a $(BUILD_STAGE)/libwasmer/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libwasmer.dylib $(BUILD_DIST)/libwasmer/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libwasmer.dylib
```

2021-07-31 17:50 UTC, TheRealKeto commented on makefiles/wasmer.mk
> +	mkdir -p $(BUILD_STAGE)/libwasmer/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib
You don't need this for the same reason line 31 works without making a bin folder.

```suggestion

```

2021-07-31 17:50 UTC, TheRealKeto commented on makefiles/wasmer.mk
> +	mkdir -p $(BUILD_STAGE)/libwasmer-dev/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/{include,lib/pkgconfig}
I suggest moving these to your setup stage instead (where GITHUB_ARCHIVE and EXTRACT_TAR goes)

2021-07-31 17:50 UTC, TheRealKeto commented on build_info/wasmer.control
> +Tag: purpose::console, role::hacker
We don't need this anymore.

```suggestion

```

2021-07-31 17:50 UTC, TheRealKeto commented on build_info/wabt.control
> +Tag: purpose::console, role::developer
We don't need this anymore, part 2

```suggestion

```

2021-07-31 17:50 UTC, TheRealKeto commented on build_info/binaryen.control
> +Tag: purpose::console, role::developer
We don't need this (part 3, better description)

```suggestion
Description: compiler and toolchain infrastructure for WebAssembly.
 Binaryen is a compiler and toolchain infrastructure library for WebAssembly,
 written in C++. It aims to make compiling to WebAssembly easy, fast, and
 effective.
Homepage: https://webassembly.org
```

2021-07-31 17:50 UTC, TheRealKeto commented on makefiles/wabt.mk
> +		-DBUILD_TESTS=OFF $(DEFAULT_CMAKE_FLAGS) \
I think you forgot to do this...

```suggestion
		$(DEFAULT_CMAKE_FLAGS) \
		-DBUILD_TESTS=OFF \
```

2021-08-10 19:54 UTC, Absolucy commented
alright, this is ready. i made `wasmer` only available on macOS, and added `wapm`.

2021-09-01 21:26 UTC, Absolucy commented
this is still ready...

2021-09-01 21:34 UTC, Absolucy commented
oh, ok. take your time, sorry for bothering you about this /genuine

2021-09-23 20:44 UTC, Absolucy commented
Sorry I uh, tend to close stuff whenever I'm in a bad mood.

2021-10-05 22:17 UTC, closed without merging