git: Add `git-credential-osxkeychain` for macOS targets
ProcursusTeam/Procursus pull request #947
Opened 2021-08-09 16:42 UTC by Absolucy

2021-08-09 17:52 UTC, DaOfficialRolex requested changes
To DEB_GIT_V add $(GIT_VERSION)-1 to it since changes were made to the makefile. I don't believe you need double quotes around every path, but it doesn't make a difference. So you can change that if you choose to.

2021-08-09 17:56 UTC, DaOfficialRolex approved these changes

2021-08-10 00:15 UTC, TheRealKeto approved these changes

2021-08-22 20:00 UTC, Shulkk approved these changes

2021-08-28 00:58 UTC, DaOfficialRolex commented
@Absolucy Please update this PR to 2.33.0 and remove the revision number. I checkout this PR on my machine and was able to confirm that it compiled as needed and works as intended.

2021-09-23 20:44 UTC, Absolucy commented
Sorry I uh, tend to close stuff whenever I'm in a bad mood.

2021-10-05 22:17 UTC, closed without merging