Add targets to build for iOS with preboot prefix
ProcursusTeam/Procursus pull request #965
Opened 2021-08-29 00:33 UTC by m1stadev

2021-08-29 00:41 UTC, CRKatri approved these changes

2021-08-29 02:00 UTC, CRKatri requested changes

2021-08-29 02:00 UTC, CRKatri commented on Makefile
> +DEB_ARCH             := iphoneos-arm
Change this to `iphoneos-arm64`

2021-08-29 02:04 UTC, m1stadev commented on Makefile
> +DEB_ARCH             := iphoneos-arm
Done.

2021-08-29 02:42 UTC, asdfugil commented
there's also watchOS, tvOS, bridgeOS and audioOS.

2021-08-29 03:27 UTC, m1stadev commented
That can be added once we know for a fact that SSV actually exists on the root volume on tvOS 15 (probably does, but should be sure, and iirc nobody's confirmed it yet)

2021-08-30 10:20 UTC, asdfugil commented
also needs iphoneos-arm migration

2021-08-30 10:32 UTC, asdfugil commented
Tweaks *should* work, accroding the situation with rootlessjb.

2021-08-30 10:38 UTC, asdfugil commented
- Automatically Move stuff to /p/p/p
  - Move stuff in /L/MS/DL to /p/p/p/lib/TweakInject
- Mach-O linked libraries header patch
  - Append /p/p/p, remove /usr for non-system libraries
  - Inject libiosexec
- Resign
- dpkg should print a warning

2021-08-30 13:55 UTC, m1stadev commented
We’re keeping `/usr`, so the path will be `/p/p/p/usr`

2021-08-30 13:57 UTC, asdfugil commented
Will we do usrmerge?

2021-09-10 15:51 UTC, merged