add snappy
ProcursusTeam/Procursus pull request #980
Opened 2021-09-05 12:13 UTC by asdfugil

2021-09-05 12:27 UTC, CRKatri requested changes

2021-09-05 12:27 UTC, CRKatri commented on makefiles/snappy.mk
> +	$(I_N_T) -change $(BUILD_STAGE)/snappy/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libsnappy-apfs.$(LIBSNAPPY_APFS_SOVER).dylib $(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libsnappy-apfs.$(LIBSNAPPY_APFS_SOVER).d
Delete this line.

2021-09-05 12:27 UTC, CRKatri commented on makefiles/snappy.mk
> +	$(CC) $(CFLAGS) $(BUILD_MISC)/libiosexec/libiosexec.1.tbd -Wl,-compatibility_version,1.0.0 -Wl,-current_version,1.3.0 -shared -framework IOKit -framework CoreFoundation -framework Foundation libsnap
Use `-install_name` and `LDFLAGS`.

2021-09-05 12:27 UTC, CRKatri commented on makefiles/snappy.mk
> +	$(CC) $(CFLAGS) $(BUILD_MISC)/libiosexec/libiosexec.1.tbd snappy.o $(BUILD_STAGE)/snappy/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/lib/libsnappy-apfs.$(LIBSNAPPY_APFS_SOVER).dylib  -framework IOKit -framewor
Use `LDFLAGS`

2021-09-05 12:27 UTC, CRKatri commented on makefiles/snappy.mk
> +	$(call SIGN,snappy,snaputil.xml)
Sign `libsnappy-apfs1` too.

2021-09-05 13:21 UTC, Diatrus commented
I don’t know that this would serve any particular use, especially with rootless on the way.

2021-09-05 13:21 UTC, asdfugil commented
USB mass storage devices exists.

2021-09-05 13:22 UTC, Diatrus commented
And what does this offer for those devices snaputil doesnt?

2021-09-05 13:25 UTC, asdfugil commented
Well it does offer more features

1. orig-fs revert shortcut
2. Show the name of the system snapshot for this boot-manifest-hash                              
3. Set the target snapshot name to be the iOS system-snapshot

2021-09-05 14:56 UTC, asdfugil commented
All right

2021-09-05 15:02 UTC, CRKatri approved these changes

2021-09-05 15:03 UTC, CRKatri commented
The PR looks good, but I agree with @Diatrus's questions about usefulness.

2021-09-05 15:04 UTC, asdfugil commented
Also, var snapshots still works

2021-09-05 15:05 UTC, CRKatri commented
`snaputil` allows specifying the volume...

2021-09-08 02:48 UTC, CRKatri commented
I'm closing this because snappy is unlicensed, so we don't have permission to redistribute.

2021-09-08 02:48 UTC, closed without merging