Fixes for shell-cmds and remove inetutils
ProcursusTeam/Procursus pull request #999
Opened 2021-09-16 17:07 UTC by Gymxo

Remove inetutils
Add pfetch ios support from upstream
Build hostname in shell-cmds

2021-09-16 17:20 UTC, Gymxo commented
Don't accept pr until remote-cmds gets added*

2021-09-16 19:06 UTC, Diatrus commented
Why remove inetutils

2021-09-16 22:54 UTC, Gymxo commented
Added remote-cmds

2021-09-16 23:03 UTC, CRKatri requested changes

2021-09-16 23:03 UTC, CRKatri commented on build_info/remote-cmds.control
> +Depends: libedit0, libiosexec1, libncursesw6
`Conflicts`, `Provides` for `inetutils`.

2021-09-16 23:03 UTC, CRKatri commented on makefiles/remote-cmds.mk
> +else ifneq (,$(findstring iphoneos,$(PLATFORM)))
```suggestion
else
```

2021-09-16 23:03 UTC, CRKatri commented on makefiles/remote-cmds.mk
> +	for tproj in logger talk talkd tftp tftpd wall; do \
Don't build these for macOS.

2021-09-16 23:03 UTC, CRKatri commented on makefiles/remote-cmds.mk
> +	wget -q -nc -P $(BUILD_BASE)/$(MEMO_PREFIX)$(MEMO_SUB_PREFIX)/include/protocols https://opensource.apple.com/source/Libc/Libc-1044.1.2/include/protocols/talkd.h
This belongs in `Makefile`

2021-09-17 09:57 UTC, Gymxo commented
Also added lukemftp (a ftp client)

2021-10-03 13:22 UTC, Gymxo commented
this pr is a mess
also I forgot that toybox existed so

2021-10-03 13:22 UTC, closed without merging